### ISSUE TITLE
Find and document anything related to Owners

### ISSUE THREAD

**Issue by linusbrown47** [GoldmanDAO/fluidity#10]

**Comment by xPi2** [comment]
Ownable contracts:
- https://github.com/GoldmanDAO/fluidity/blob/main/packages/contracts/contracts/TroveManager.sol
- https://github.com/GoldmanDAO/fluidity/blob/main/packages/contracts/contracts/StabilityPool.sol
- https://github.com/GoldmanDAO/fluidity/blob/main/packages/contracts/contracts/SortedTroves.sol
- https://github.com/GoldmanDAO/fluidity/blob/main/packages/contracts/contracts/PriceFeed.sol
- https://github.com/GoldmanDAO/fluidity/blob/main/packages/contracts/contracts/HintHelpers.sol
- https://github.com/GoldmanDAO/fluidity/blob/main/packages/contracts/contracts/DefaultPool.sol
- https://github.com/GoldmanDAO/fluidity/blob/main/packages/contracts/contracts/CollSurplusPool.sol
- https://github.com/GoldmanDAO/fluidity/blob/main/packages/contracts/contracts/BorrowerOperations.sol
- https://github.com/GoldmanDAO/fluidity/blob/main/packages/contracts/contracts/ActivePool.sol
- https://github.com/GoldmanDAO/fluidity/blob/main/packages/contracts/contracts/LQTY/LQTYStaking.sol
- https://github.com/GoldmanDAO/fluidity/blob/main/packages/contracts/contracts/LQTY/CommunityIssuance.sol

All contracts use ownership to set addresses and immediately after renounce ownership.

**Comment by xPi2** [comment]
Its not related to actual ownership of the contracts but how the initial ownership of the protocol's token, LQTY is issued.
You can check the architecture and launching sequence here: https://github.com/GoldmanDAO/fluidity#lqty-token-architecture

On LQTY deployment:
- 2M LQTY is allocated for future bounties through a "bountyAddress", no vesting.
- 32M LQTY is allocated to the **CommunityIssuance**, this will be algorithmically distributed to the stability providers. 
- 1.33M LQTY is allocated to the LP Rewards through **UniPool**, this will be distributed to the LP providers during the rewards program.
- 64.66M LQTY is allocated to the admin multisig, during the first year can only be redistributed to Lockup contracts with a vesting period of at least 1 year since system deployment.

A total of 100M LQTY supply is distributed on creation, future supply is only issued through Troves.
