### ISSUE TITLE
Document issues or things to know when running tests

### ISSUE THREAD

**Issue by linusbrown47** [GoldmanDAO/fluidity#8]

**Comment by xPi2** [comment]
Running all tests is painfully slow, not recommended.

**Comment by EnriqCG** [comment]
It is not clearly stated on the README but a local OpenEthereum container needs to be running on Docker in order to deploy contracts and these them successfully.

There are a total of 58 tests on the `@liquity/lib-base` workspace.
There are a total of 51 tests on the `@liquity/lib-ethers` workspace.

All tests run succesfully with the current state of the repo @https://github.com/GoldmanDAO/fluidity/commit/d97ca8c9fc378c94b8393d8880efd1193cd48aa8.

See #22 for insight as to why tests were failing
