### ISSUE TITLE
Document anything related with timestamps or block speeds

### ISSUE THREAD

**Issue by linusbrown47** [GoldmanDAO/fluidity#9]
This new blockchain we're porting to most likely will have different time per block, so if the contracts are doing any validation like "you can't take a loan after the 5 first minutes after deposit" or things like that, it might break in this new chain. Depends on the implementation, so you'll need to read the code for that part.

Things to look for:
- Suffixes like seconds, minutes, hours, days and weeks. These should work, but I don't trust these guys, so let's test any line containing any of these words.
- block.difficulty
- block.number
- block.timestamp

**Comment by xPi2** [comment]
Timestamp dependencies to take into consideration:

- **PriceFeed** uses `block.timestamp` to check the validity of the Chainlink / Tellor response. There is a hardcoded `TIMESTAMP` of 4 hours that set the maximum time passed allowed since the last data update of Chainlink / Tellor, after that they are considered frozen and their data can't be used.
- **LQTYToken** uses `timestamp` to check for the vesting time of the protocol (1 year) during which transfers from the admin safe are restricted to Lockup contracts.
- **LockupContract** uses `timestamp` to check for the unlock of the funds allocated on the contract.
- **CommunityIssuance** uses `timestamp` to compute the cumulative issuance at any time, the delta between the deployment and current time is used as `timePassedInMinutes`.
- **TroveManager** uses `timestamp` to update the `lastFeeOperationTime` updating operational fees accordingly, also uses `timestamp` to restrict the redemption operation until the `BOOTSTRAP_PERIOD` of 14 days has passed.
- **UniPool** uses `timestamp` to compute the `rewardPerToken`
